server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # Serve static assets directly
  location /assets/ {
    try_files $uri =404;
  }

  # SPA fallback for frontend routes
  location / {
    try_files $uri $uri/ /index.html;
  }
}
