name: Backend Release (Tag → Build → Scan → Deploy)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  build-scan-push-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Release Version = $VERSION"
    
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/felixopk/ecommerce-backend:${{ steps.version.outputs.version }} backend
    
    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push Image to GHCR
      run: |
        docker push ghcr.io/felixopk/ecommerce-backend:${{ steps.version.outputs.version }}
    
    - name: Security Scan with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image \
          --severity HIGH,CRITICAL \
          --format table \
          --exit-code 0 \
          ghcr.io/felixopk/ecommerce-backend:${{ steps.version.outputs.version }}
    
    - name: Update and Apply Deployment
      run: |
        sed -i "s#ghcr.io/felixopk/ecommerce-backend:.*#ghcr.io/felixopk/ecommerce-backend:${{ steps.version.outputs.version }}#g" kubernetes/backend-deployment.yaml
        kubectl apply -f kubernetes/backend-deployment.yaml
        echo "✅ Deployed backend:${{ steps.version.outputs.version }} to cluster"