name: Frontend Release (Tag → Build → Scan → Deploy)

on:
  push:
    tags:
      - "frontend-v*.*.*"  # Triggers on tags like frontend-v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build-scan-push-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/frontend-}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Release Version = $VERSION"
    
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/felixopk/ecommerce-frontend:${{ steps.version.outputs.version }} frontend/ecommerce-frontend
    
    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push Image to GHCR
      run: |
        docker push ghcr.io/felixopk/ecommerce-frontend:${{ steps.version.outputs.version }}
    
    - name: Security Scan with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy image \
          --severity HIGH,CRITICAL \
          --format table \
          --exit-code 0 \
          ghcr.io/felixopk/ecommerce-frontend:${{ steps.version.outputs.version }}
    
    - name: Update Kubernetes Deployment Image Tag
      run: |
        sed -i "s#ghcr.io/felixopk/ecommerce-frontend:.*#ghcr.io/felixopk/ecommerce-frontend:${{ steps.version.outputs.version }}#g" kubernetes/frontend-deployment.yaml
    
    - name: Commit Updated Manifest
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add kubernetes/frontend-deployment.yaml
        git commit -m "chore: update frontend image to ${{ steps.version.outputs.version }}" || echo "No changes"
        git push
    
    - name: Apply Deployment to Cluster
      run: |
        kubectl apply -f kubernetes/frontend-deployment.yaml
